import { precacheAndRoute } from 'workbox-precaching'
import { registerRoute } from 'workbox-routing'
import { NetworkFirst, CacheFirst } from 'workbox-strategies'

// Inject the precache manifest generated by Vite PWA
precacheAndRoute(self.__WB_MANIFEST)

// Force service worker to activate immediately on install
self.addEventListener('install', () => {
  self.skipWaiting()
})

// Claim clients to immediately control them without reload
self.addEventListener('activate', (event) => {
  event.waitUntil(self.clients.claim())
})

// ─── HTML: Network-First — immer frische Version, Cache nur als Fallback ───
registerRoute(
  ({ request }) => request.destination === 'document',
  new NetworkFirst({ cacheName: 'html-cache', networkTimeoutSeconds: 5 })
)

// ─── JS/CSS/Fonts/Images: Cache-First mit Background-Update ───
registerRoute(
  ({ request }) => ['script', 'style', 'font', 'image'].includes(request.destination),
  new CacheFirst({ cacheName: 'assets-cache' })
)

// Handle push events
self.addEventListener('push', (event) => {
  if (!event.data) return

  try {
    const data = event.data.json()
    
    const title = data.title || 'SuperBET'
    const options = {
      body: data.body || 'Neue Benachrichtigung',
      icon: '/pwa-192x192.png',
      badge: '/pwa-192x192.png',
      vibrate: [200, 100, 200],
      data: { url: data.url || '/' }
    }

    event.waitUntil(
      self.registration.showNotification(title, options)
    )
  } catch (err) {
    console.error('Error parsing push event data:', err)
  }
})

// Handle notification click
self.addEventListener('notificationclick', (event) => {
  event.notification.close()
  
  const urlToOpen = event.notification.data.url || '/'
  
  event.waitUntil(
    self.clients.matchAll({ type: 'window', includeUncontrolled: true }).then((windowClients) => {
      // If a window is already open, focus it and navigate
      for (let i = 0; i < windowClients.length; i++) {
        const client = windowClients[i]
        if (client.url.includes(urlToOpen) && 'focus' in client) {
          client.navigate(urlToOpen)
          return client.focus()
        }
      }
      // If no window is open, open a new one
      if (self.clients.openWindow) {
        return self.clients.openWindow(urlToOpen)
      }
    })
  )
})
