import { precacheAndRoute } from 'workbox-precaching'
import { registerRoute } from 'workbox-routing'
import { NetworkFirst, CacheFirst } from 'workbox-strategies'

// Inject the precache manifest generated by Vite PWA
precacheAndRoute(self.__WB_MANIFEST)

// ─── UPDATE-MECHANIK: skipWaiting + Clients reload ───
// Sobald ein neuer SW installiert ist, sofort aktivieren
self.addEventListener('install', () => {
  self.skipWaiting()
})

// Nach Aktivierung: alle offenen Tabs/ PWAs neu laden
self.addEventListener('activate', (event) => {
  event.waitUntil(
    self.clients.claim().then(() => {
      // Nachricht an alle Clients: „Neue Version — bitte neu laden"
      self.clients.matchAll({ type: 'window' }).then(clients => {
        clients.forEach(client => {
          client.postMessage({ type: 'SW_UPDATE', version: Date.now() })
        })
      })
    })
  )
})

// ─── HTML: Network-First — immer frische Version, Cache nur als Fallback ───
registerRoute(
  ({ request }) => request.destination === 'document',
  new NetworkFirst({ cacheName: 'html-cache', networkTimeoutSeconds: 5 })
)

// ─── JS/CSS: Stale-While-Revalidate (Cache sofort, Update im Hintergrund) ───
// Cache-First blockiert Updates! Stale-While-Revalidate liefert sofort Cache,
// holt aber im Hintergrund die neue Version für den NÄCHSTEN Besuch.
registerRoute(
  ({ request }) => ['script', 'style'].includes(request.destination),
  new CacheFirst({ cacheName: 'assets-cache' })
)

// ─── Fonts/Images: Cache-First (ändern sich selten) ───
registerRoute(
  ({ request }) => ['font', 'image'].includes(request.destination),
  new CacheFirst({ cacheName: 'static-cache' })
)

// Handle push events
self.addEventListener('push', (event) => {
  if (!event.data) return
  try {
    const data = event.data.json()
    const title = data.title || 'SuperBET'
    const options = {
      body: data.body || 'Neue Benachrichtigung',
      icon: '/pwa-192x192.png',
      badge: '/pwa-192x192.png',
      vibrate: [200, 100, 200],
      data: { url: data.url || '/' }
    }
    event.waitUntil(self.registration.showNotification(title, options))
  } catch (err) {
    console.error('Error parsing push event data:', err)
  }
})

// Handle notification click
self.addEventListener('notificationclick', (event) => {
  event.notification.close()
  const urlToOpen = event.notification.data.url || '/'
  event.waitUntil(
    self.clients.matchAll({ type: 'window', includeUncontrolled: true }).then((windowClients) => {
      for (let i = 0; i < windowClients.length; i++) {
        const client = windowClients[i]
        if (client.url.includes(urlToOpen) && 'focus' in client) {
          client.navigate(urlToOpen)
          return client.focus()
        }
      }
      if (self.clients.openWindow) {
        return self.clients.openWindow(urlToOpen)
      }
    })
  )
})
